services:
  extafia:
    image: ghcr.io/unexistencer/extafia-bot:${IMAGE_TAG:-latest}
    pull_policy: always

    container_name: extafia
    restart: unless-stopped

    env_file:
      - .env

    environment:
      TZ: ${TZ}

    volumes:
      - ./logs:/app/logs